# -*- coding: utf-8 -*-
"""Monterrey- Weather-cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JcRrW6zDNQUMxw-mDZRY48STZgyeqq9l
"""

import pandas as pd
import os
import numpy as np

df = pd.read_csv(r"C:\Users\nilou\OneDrive\Documents\PhD-Tec\PhD proposal\Papers\P03-Future weather\Weather test\NOAA\Downloaded\SAn diego-MexcioC\72290023188 (7).csv")
df

"""# New Section"""

df = df[['DATE', 'WND', 'TMP', 'DEW', 'SLP']]

# Print the resulting DataFrame
print(df)

# replace "T" with a space in the Date column
df["DATE"] = df["DATE"].str.replace("T", " ")

# convert the Date column to datetime format
df["DATE"] = pd.to_datetime(df["DATE"])

# display the updated dataframe
print(df.head())

df['TMP'] = df['TMP'].str.replace(r',.*', '').astype(float) / 10
print(df.head())

df['DEW'] = df['DEW'].str.replace(',', '').str.replace('\d$', '').str.replace('+', '').astype(float)/10
print(df.head())

df['SLP'] = df['SLP'].str.replace(',', '').str.replace('\d$', '').astype(float)/10
print(df.head())

df['WND'] = df['WND'].str.split(',', n=1, expand=True)[0].astype(float)/100
print(df.head())

import numpy as np

df.replace({'WND': [100, 9.99, 999.9, 9999.9], 'TMP': [100, 9.99, 999.9, 9999.9], 'DEW': [100, 9.99, 999.9, 9999.9], 'SLP': [100, 9.99, 9999.9, 99999.9]}, np.nan, inplace=True)
print(df.head())

df['DATE'] = df['DATE'].dt.floor('H')
print(df.head())

df = df.groupby([pd.Grouper(key='DATE', freq='H'), df['DATE'].dt.hour]).mean().reset_index(level=1, drop=True).reset_index()
print(df.head())

df.to_csv("output.csv", index=False)

cwd = os.getcwd()

# construct the file path to where the CSV file was saved
file_path = os.path.join(cwd, 'output.csv')

print(file_path) # print the file path

"""How to do it for group of files?"""

import pandas as pd
import numpy as np
import os

# Directory where all csv files are located
dir_path = r"C:\Users\nilou\OneDrive\Documents\PhD-Tec\PhD proposal\Papers\P03-Future weather\Weather test\NOAA\Downloaded\Miami-veracruz"
new_path = r"C:\Users\nilou\OneDrive\Documents\PhD-Tec\PhD proposal\Papers\P03-Future weather\Weather test\NOAA\Clean data\Colab VCZ"

# Loop through all csv files in the directory
for file_name in os.listdir(dir_path):
    if file_name.endswith(".csv"):
        file_path = os.path.join(dir_path, file_name)

        # Read csv file into a pandas dataframe
        df = pd.read_csv(file_path)

        # Perform the same operations as before
        df = df[['DATE', 'WND', 'TMP', 'DEW', 'SLP']]
        # replace "T" with a space in the Date column
        df["DATE"] = df["DATE"].str.replace("T", " ")
        df["DATE"] = pd.to_datetime(df["DATE"])
        df['TMP'] = df['TMP'].str.replace(r',.*', '').astype(float) / 10
        df['DEW'] = df['DEW'].str.replace(r',.*', '').astype(float) / 10
        df['SLP'] = df['SLP'].str.replace(',', '').str.replace('\d$', '').astype(float)/10
        df['WND'] = df['WND'].str.split(',', n=1, expand=True)[0].astype(float)/100
        df.replace({'WND': [100, 9.99, 999.9, 9999.9], 'TMP': [100, 9.99, 999.9, 9999.9], 'DEW': [100, 9.99, 999.9, 9999.9], 'SLP': [100, 9.99, 9999.9, 99999.9]}, np.nan, inplace=True)
        df['DATE'] = df['DATE'].dt.floor('H')
        df = df.groupby([pd.Grouper(key='DATE', freq='H'), df['DATE'].dt.hour]).mean().reset_index(level=1, drop=True).reset_index()

        # Save the updated dataframe as a new csv file
        new_file_name = file_name.split(".")[0] + "_updated.csv"
        new_file_path = os.path.join(new_path, new_file_name)
        df.to_csv(new_file_path, index=False)

import pandas as pd
import os

# Directory where all csv files are located
dir_path = r"C:\Users\nilou\OneDrive\Documents\PhD-Tec\PhD proposal\Papers\P03-Future weather\Weather test\NOAA\Clean data\Colab VCZ"

# Create a list of all csv files in the directory
csv_files = [f for f in os.listdir(dir_path) if f.endswith(".csv")]

# Sort the csv files in ascending order based on their file name
csv_files.sort()

# Combine all csv files into a single dataframe
df_combined = pd.concat([pd.read_csv(os.path.join(dir_path, f)) for f in csv_files])

# Save the combined dataframe as a new csv file
combined_file_path = os.path.join(dir_path, "combined_data.csv")
df_combined.to_csv(combined_file_path, index=False)